[package]
name = "mdr_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.8.0"
cgmath = "0.18.0"
image = "0.24.0"
log = "0.4.17"
tobj = "3.2.2"
vulkano = "0.29.0"
vulkano-shaders = "0.29.0"
vulkano-win = "0.29.0"
winit = "0.26.1"