name: MD Render automatic build and release

# Release when a tag like v0.1.0 is pushed
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  # Build application and upload artifact
  build-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: md-render-release
          path: target/release/

  # Download artifact and create release
  release:
    needs: build-prod
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true 
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: release-${{ github.ref }}
          body_path: changelog.md

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: md-render-release
          path: artifact

      - name: Zip artifact
        run: |
          sudo apt-get install -y zip
          zip -r artifact/prod-artifact.zip artifact

      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        id: upload_release_asset 
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact/prod-artifact.zip 
          asset_name: MD-Render.zip
          asset_content_type: application/zip
